// Typed wrappers around Wails Go bindings

import { Version, HasRepository, InitRepository, OpenRepository, CloseRepository,
  PickFolder, ListRecentRepos, RemoveRecentRepo,
  CreateBrand, GetBrand, ListBrands, RenameBrand, DeleteBrand,
  CreateStream, ListStreams, RenameStream, DeleteStream,
  CreateProject, ListProjects, RenameProject, DeleteProject,
  CreateCategory, ListCategories, RenameCategory, DeleteCategory, MoveCategoryCards, CopyCategory,
  CreateCard, GetCard, ListCards, DeleteCard, DuplicateCard,
  UpdateCardTitle, UpdateCardFields, UpdateCardTags, UpdateCardDueDate,
  AddChecklistItem, ToggleChecklistItem, RemoveChecklistItem,
  PinCard, UnpinCard, GetCardPins,
  MoveCardInCategory, MoveCardToCategory, ReorderBrands, ReorderStreams, ReorderProjects, ReorderCategories,
  MoveProject, MoveStream, CopyBrand, CopyStream, CopyProject,
  GetTagColors, SetTagColor, AssignTagColor,
  ListCardTypes, ValidateCardFields,
  SearchCards, RebuildIndex, RefreshIndex,
  ListCardIDsInCategory, ListCardIDsByTag,
  GetPreferences, SetPreferences,
  GetProfile, SetProfile,
} from '../../wailsjs/go/main/App.js'

export {
  Version, HasRepository, InitRepository, OpenRepository, CloseRepository,
  PickFolder, ListRecentRepos, RemoveRecentRepo,
  CreateBrand, GetBrand, ListBrands, RenameBrand, DeleteBrand,
  CreateStream, ListStreams, RenameStream, DeleteStream,
  CreateProject, ListProjects, RenameProject, DeleteProject,
  CreateCategory, ListCategories, RenameCategory, DeleteCategory, MoveCategoryCards, CopyCategory,
  CreateCard, GetCard, ListCards, DeleteCard, DuplicateCard,
  UpdateCardTitle, UpdateCardFields, UpdateCardTags, UpdateCardDueDate,
  AddChecklistItem, ToggleChecklistItem, RemoveChecklistItem,
  PinCard, UnpinCard, GetCardPins,
  MoveCardInCategory, MoveCardToCategory, ReorderBrands, ReorderStreams, ReorderProjects, ReorderCategories,
  MoveProject, MoveStream, CopyBrand, CopyStream, CopyProject,
  GetTagColors, SetTagColor, AssignTagColor,
  ListCardTypes, ValidateCardFields,
  SearchCards, RebuildIndex, RefreshIndex,
  ListCardIDsInCategory, ListCardIDsByTag,
  GetPreferences, SetPreferences,
  GetProfile, SetProfile,
}
