/**
 * Curated icon map for the icon picker system.
 * IMPORTANT: Do NOT use `import * from lucide-svelte` — that bloats the bundle.
 * Only import icons that are explicitly listed here.
 */
import {
  Folder, FolderOpen, Star, Heart, Zap, Rocket, Globe,
  Home, User, Users, Settings, Bell, Mail, MessageSquare,
  FileText, File, Image, Video, Music, Camera, Mic,
  Book, BookOpen, Bookmark, Tag, Tags, Flag,
  Calendar, Clock, Timer, AlertCircle, CheckCircle,
  ArrowRight, ArrowUp, Link, ExternalLink,
  Code, Terminal, Database, Server, Cloud,
  ShoppingCart, DollarSign, CreditCard, BarChart3, PieChart,
  Briefcase, Building, Award, Target, Crosshair,
  Sun, Moon, Sparkles, Flame, Leaf, TreePine,
  Tv, Radio, Podcast, Headphones, Gamepad2,
  Palette, Pen, PenTool, Brush, Scissors,
  Map, MapPin, Compass, Navigation,
  Lock, Unlock, Key, Shield, Eye,
  Phone, Smartphone, Monitor, Laptop,
  Gift, PartyPopper, Megaphone, HandMetal,
  Lightbulb, Puzzle, Wrench, Hammer, CircleDot,
  Hash, AtSign, Percent, Binary,
} from 'lucide-svelte'

type IconComponent = typeof Folder

export const ICON_MAP: Record<string, IconComponent> = {
  'folder': Folder,
  'folder-open': FolderOpen,
  'star': Star,
  'heart': Heart,
  'zap': Zap,
  'rocket': Rocket,
  'globe': Globe,
  'home': Home,
  'user': User,
  'users': Users,
  'settings': Settings,
  'bell': Bell,
  'mail': Mail,
  'message-square': MessageSquare,
  'file-text': FileText,
  'file': File,
  'image': Image,
  'video': Video,
  'music': Music,
  'camera': Camera,
  'mic': Mic,
  'book': Book,
  'book-open': BookOpen,
  'bookmark': Bookmark,
  'tag': Tag,
  'tags': Tags,
  'flag': Flag,
  'calendar': Calendar,
  'clock': Clock,
  'timer': Timer,
  'alert-circle': AlertCircle,
  'check-circle': CheckCircle,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'link': Link,
  'external-link': ExternalLink,
  'code': Code,
  'terminal': Terminal,
  'database': Database,
  'server': Server,
  'cloud': Cloud,
  'shopping-cart': ShoppingCart,
  'dollar-sign': DollarSign,
  'credit-card': CreditCard,
  'bar-chart': BarChart3,
  'pie-chart': PieChart,
  'briefcase': Briefcase,
  'building': Building,
  'award': Award,
  'target': Target,
  'crosshair': Crosshair,
  'sun': Sun,
  'moon': Moon,
  'sparkles': Sparkles,
  'flame': Flame,
  'leaf': Leaf,
  'tree-pine': TreePine,
  'tv': Tv,
  'radio': Radio,
  'podcast': Podcast,
  'headphones': Headphones,
  'gamepad2': Gamepad2,
  'palette': Palette,
  'pen': Pen,
  'pen-tool': PenTool,
  'brush': Brush,
  'scissors': Scissors,
  'map': Map,
  'map-pin': MapPin,
  'compass': Compass,
  'navigation': Navigation,
  'lock': Lock,
  'unlock': Unlock,
  'key': Key,
  'shield': Shield,
  'eye': Eye,
  'phone': Phone,
  'smartphone': Smartphone,
  'monitor': Monitor,
  'laptop': Laptop,
  'gift': Gift,
  'party-popper': PartyPopper,
  'megaphone': Megaphone,
  'hand-metal': HandMetal,
  'lightbulb': Lightbulb,
  'puzzle': Puzzle,
  'wrench': Wrench,
  'hammer': Hammer,
  'circle-dot': CircleDot,
  'hash': Hash,
  'at-sign': AtSign,
  'percent': Percent,
  'binary': Binary,
}

export const AVAILABLE_ICONS = Object.keys(ICON_MAP)

export const ICON_CATEGORIES: Record<string, string[]> = {
  'General': ['folder', 'folder-open', 'star', 'heart', 'zap', 'rocket', 'globe', 'home', 'flag', 'bookmark', 'tag', 'tags', 'lightbulb', 'puzzle', 'circle-dot'],
  'People': ['user', 'users', 'hand-metal'],
  'Communication': ['bell', 'mail', 'message-square', 'megaphone', 'phone', 'smartphone'],
  'Media': ['image', 'video', 'music', 'camera', 'mic', 'tv', 'radio', 'podcast', 'headphones', 'gamepad2'],
  'Files': ['file-text', 'file', 'book', 'book-open', 'pen', 'pen-tool', 'brush', 'scissors', 'palette'],
  'Dev': ['code', 'terminal', 'database', 'server', 'cloud', 'hash', 'at-sign', 'binary'],
  'Business': ['briefcase', 'building', 'shopping-cart', 'dollar-sign', 'credit-card', 'bar-chart', 'pie-chart', 'award', 'target', 'crosshair'],
  'Time': ['calendar', 'clock', 'timer'],
  'Nature': ['sun', 'moon', 'sparkles', 'flame', 'leaf', 'tree-pine'],
  'Navigation': ['map', 'map-pin', 'compass', 'navigation', 'arrow-right', 'arrow-up', 'link', 'external-link'],
  'Security': ['lock', 'unlock', 'key', 'shield', 'eye'],
  'Devices': ['monitor', 'laptop', 'settings'],
  'Status': ['alert-circle', 'check-circle'],
  'Fun': ['gift', 'party-popper', 'wrench', 'hammer', 'percent'],
}
