import type { BackendAdapter, EventCallback } from '../types'

import {
  Version, HasRepository, InitRepository, OpenRepository, CloseRepository,
  PickFolder, ListRecentRepos, RemoveRecentRepo,
  CreateBrand, GetBrand, ListBrands, RenameBrand, DeleteBrand,
  CreateStream, ListStreams, RenameStream, DeleteStream,
  CreateProject, ListProjects, RenameProject, DeleteProject,
  CreateCategory, ListCategories, RenameCategory, DeleteCategory, MoveCategoryCards, CopyCategory, UpdateCategoryAcceptedTypes,
  CreateCard, GetCard, ListCards, DeleteCard, DuplicateCard,
  UpdateCardTitle, UpdateCardType, UpdateCardFields, UpdateCardBlocks, UpdateCardTags, UpdateCardLabels, UpdateCardDueDate,
  AddChecklistItem, ToggleChecklistItem, RemoveChecklistItem,
  PinCard, UnpinCard, GetCardPins, GetCardLocation, GetProjectLocation,
  ListAllCategories, GetCardPinBreadcrumbs,
  MoveCardInCategory, MoveCardToCategory, ReorderBrands, ReorderStreams, ReorderProjects, ReorderCategories,
  MoveProject, MoveStream, CopyBrand, CopyStream, CopyProject,
  GetTagColors, SetTagColor, AssignTagColor,
  GetProjectLabels, AddProjectLabel, RemoveProjectLabel, UpdateProjectLabel,
  ListCardTypes, ValidateCardFields,
  CreateUserCardType, UpdateUserCardType, DeleteUserCardType, UpdateBuiltinCardType,
  ListCardTemplates, CreateCardTemplate, UpdateCardTemplate, DeleteCardTemplate,
  SearchCards, SearchOrphanedCards, GetCardProjectContext, RebuildIndex, RefreshIndex,
  ListCardIDsInCategory, ListOrphanedCardIDs, ListCardIDsByTag,
  GetPreferences, SetPreferences,
  GetProfile, SetProfile,
  GetAuthInfo, GetLLMConfig, SetLLMConfig,
  LoadChatHistory, SendChatMessage,
  IsLLMConfigured, TestLLMConnection,
  AcceptPinSuggestion, RejectPinSuggestion,
  AcceptPendingEdit, RejectPendingEdit, AcceptAllPendingEdits, RejectAllPendingEdits, ApplyPendingEdits,
  // @ts-ignore — generated after `wails generate` with updated Go code
  AddCardAttachment,
  // @ts-ignore — generated after `wails generate` with updated Go code
  RemoveCardAttachment,
  // @ts-ignore — generated after `wails generate` with updated Go code
  ListActivityLog,
  // @ts-ignore — generated after `wails generate` with updated Go code
  ListRecentlyUpdatedCards,
} from '../../../wailsjs/go/main/App.js'

export const wailsAdapter: BackendAdapter = {
  getCapabilities: () => ({
    hasLocalFilesystem: true,
    hasAuth: false,
    hasRealtime: false,
  }),

  GetAuthInfo,
  GetProfile,
  SetProfile,
  GetLLMConfig,
  SetLLMConfig,

  subscribe(_cb: EventCallback) {},
  unsubscribe(_cb: EventCallback) {},

  Version,
  HasRepository,
  InitRepository,
  OpenRepository,
  CloseRepository,
  PickFolder,
  ListRecentRepos,
  RemoveRecentRepo,

  CreateBrand,
  GetBrand,
  ListBrands,
  RenameBrand,
  DeleteBrand,

  CreateStream,
  ListStreams,
  RenameStream,
  DeleteStream,

  CreateProject,
  ListProjects,
  RenameProject,
  DeleteProject,

  CreateCategory,
  ListCategories,
  RenameCategory,
  DeleteCategory,
  MoveCategoryCards,
  CopyCategory,
  UpdateCategoryAcceptedTypes,

  CreateCard,
  GetCard,
  ListCards,
  DeleteCard,
  DuplicateCard,

  UpdateCardTitle,
  UpdateCardType,
  UpdateCardFields,
  UpdateCardBlocks,
  UpdateCardTags,
  UpdateCardLabels,
  UpdateCardDueDate,

  AddChecklistItem,
  ToggleChecklistItem,
  RemoveChecklistItem,

  PinCard,
  UnpinCard,
  GetCardPins,
  GetCardLocation,
  GetProjectLocation,
  ListAllCategories,
  GetCardPinBreadcrumbs,

  MoveCardInCategory,
  MoveCardToCategory,
  ReorderBrands,
  ReorderStreams,
  ReorderProjects,
  ReorderCategories,

  MoveProject,
  MoveStream,
  CopyBrand,
  CopyStream,
  CopyProject,

  GetTagColors,
  SetTagColor,
  AssignTagColor,

  GetProjectLabels,
  AddProjectLabel,
  RemoveProjectLabel,
  UpdateProjectLabel,

  ListCardTypes: ListCardTypes as BackendAdapter['ListCardTypes'],
  ValidateCardFields,
  CreateUserCardType,
  UpdateUserCardType,
  DeleteUserCardType,
  UpdateBuiltinCardType,
  ListCardTemplates: ListCardTemplates as unknown as BackendAdapter['ListCardTemplates'],
  CreateCardTemplate: CreateCardTemplate as unknown as BackendAdapter['CreateCardTemplate'],
  UpdateCardTemplate: UpdateCardTemplate as unknown as BackendAdapter['UpdateCardTemplate'],
  DeleteCardTemplate,

  SearchCards,
  SearchOrphanedCards,
  GetCardProjectContext,
  RebuildIndex,
  RefreshIndex,
  ListCardIDsInCategory,
  ListOrphanedCardIDs,
  ListCardIDsByTag,

  LoadChatHistory,
  SendChatMessage,
  IsLLMConfigured,
  TestLLMConnection,
  AcceptPinSuggestion,
  RejectPinSuggestion,
  AcceptPendingEdit,
  RejectPendingEdit,
  AcceptAllPendingEdits,
  RejectAllPendingEdits,
  ApplyPendingEdits,

  AddCardAttachment: AddCardAttachment as unknown as BackendAdapter['AddCardAttachment'],
  RemoveCardAttachment: RemoveCardAttachment as unknown as BackendAdapter['RemoveCardAttachment'],

  GetPreferences,
  SetPreferences,

  ListActivityLog: ListActivityLog as unknown as BackendAdapter['ListActivityLog'],
  ListRecentlyUpdatedCards: ListRecentlyUpdatedCards as unknown as BackendAdapter['ListRecentlyUpdatedCards'],
}
